### ISSUE TITLE
Vehicle preview bug

### ISSUE THREAD

**Issue by Loko415** [Yimura/YimMenu#119]
**Describe the bug**
vehicle preview bug

**To Reproduce**
1. Go to spawner
2. Click on a vehicle
3. it shows the preview. search for another vehicle and its preview wont show. The old vehicle will only show. Fixed by closing and opening menu using insert

**Expected behavior**
it instantly switches to a new cars preview. Also noticed sometimes it shows the wrong car

**Screenshots**
none right now. But you can check yourself

**Logs**

no<paste your logs here>
no

**Build**
Select which applies for you:
- [ ] I used YimMenu unmodified
- [X] I use my own version of YimMenu

**Additional context**
none

**Comment by Loko415** [comment]
i didnt assign you my bad idk why it said that

**Comment by Yimura** [comment]
There might be a way to fix that but yes currently the vehicle preview is janky in certain ways.

1. Unloading while previewing leaves the vehicle behind
2. When scrolling the preview will sometimes show the incorrect vehicle, to fix this go of the list with your cursor and back on the list.
3. Swapping between tabs keeps the vehicles previewed

**Comment by Mystro69** [comment]
#170 it should be fixed

**Comment by Yimura** [comment]
> #170 it should be fixed

Yes but the issue remains open because of my comment mentioning other issues with the vehicle preview.
The main problem still being that the vehicle preview remains active when switching tabs.

**Comment by LiamD-Flop** [comment]
Implemented by #226
