### ISSUE TITLE
[Bug]: Bring player still glitches

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#1501]
### Describe the bug

Although I thought this was fixed, using bring player on a player (CVehicleProximityMigrationDataNode) results in the player teleporting time after time to the same location. I believe the sync is still being sent with the player as the occupant.

### Steps To Reproduce

1.Press bring on an on-foot player
2.Observe them (sometimes this also doesn't work) teleport
3.Watch out for the consecutive teleports.

### Expected Behavior

After teleporting a player, the node should not be sent with the same data.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by vincentix** [comment]
I can confirm this is still a bug as of 6-23 1:23AM CST

**Comment by fakedafuq1st** [comment]
can confirm still buggy.

**Comment by Modyes** [comment]
Brought player also gets teleported into random vehicles for some reason even though I've never used such an option

**Comment by Yimura** [comment]
Should be fixed by #1533 

Nvm, this is about the cleanup of the bring player feature and not really about the protection randomly working.

**Comment by Yimura** [comment]
Should be fixed by #1785

**Comment by gir489returns** [comment]
> Should be fixed by #1785

Partially. Step 2's addendum that Bring fails to work sometimes still occurs.
