### ISSUE TITLE
[Bug]: After finishing the robbery mission, it shows "unable to join the battle". I don't know if it is Yim's problem or network problem?

### ISSUE THREAD

**Issue by aierxiya** [Yimura/YimMenu#1638]
### Describe the bug

After finishing the robbery mission, it shows "unable to join the battle". I don't know if it is Yim's problem or network problem?

### Steps To Reproduce

After going to the settlement page, a pop-up "Cannot join the online battle" and switch to offline

### Expected Behavior

Join the battle normally

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment]
I believe this was addressed with #1635. Can you retest with the latest build?

**Comment by aierxiya** [comment]
use 2f1f094，Still showing "failed to join the battle" or "failed to join the planned battle"
