### ISSUE TITLE
[Bug]: Unloading The Menu Causes CTD.

### ISSUE THREAD

**Issue by xesdoog** [Yimura/YimMenu#2786]
### Describe the bug

Since the first time I've ever used the menu, I always had a crash to desktop issue every time I unload it. I didn't report it before because it seemed specific to my setup and I thought it wasn't a big deal but now I found myself needing to unload the menu more often for testing purposes.

### Steps To Reproduce

-  Launch the game.
- Join a session _(I always play in invite-only)_.
- Inject YimMenu and wait for it to load properly.
- Unload -> Crash To Desktop.

### Expected Behavior

Safely unload without crashing. 

### Logs and/or screenshots

```
<paste your logs here>
```
[15:17:34.3792283][INFO/main.cpp:159] Yim's Menu Initializing
[15:17:34.3792559][INFO/main.cpp:160] Git Info
	Branch:	master
	Hash:	a6a77a0f6baf1c1376b25af09ded9dda894b6490
	Date:	Thu Feb 22 09:34:41 2024
[15:17:34.3793577][INFO/main.cpp:172] Windows 11 Pro Version 23H2 (OS Build 22631.3155)
[15:17:34.3817670][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[15:17:34.3819240][INFO/main.cpp:180] Thread pool initialized.
[15:17:34.3847109][INFO/main.cpp:183] Settings Loaded.
[15:17:34.3847165][DEBUG/thread_pool.cpp:96] Thread 18620 executing settings.cpp:12
[15:17:34.3856466][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[15:17:34.3856613][INFO/pointers.cpp:1830] Loading pointers instance from cache
[15:17:34.3856634][INFO/pointers.cpp:1839] Pointers cache: Loading 217 fields from the cache
[15:17:34.3856728][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[15:17:34.3864261][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[15:17:34.3864327][INFO/pointers.cpp:1830] Loading pointers instance from cache
[15:17:34.3864349][INFO/pointers.cpp:1839] Pointers cache: Loading 5 fields from the cache
[15:17:34.3864818][INFO/main.cpp:186] Pointers initialized.
[15:17:34.3864941][INFO/main.cpp:193] Disabled anticheat gameskeleton.
[15:17:34.3869399][INFO/main.cpp:196] Byte Patch Manager initialized.
[15:17:34.4261570][INFO/main.cpp:199] Renderer initialized.
[15:17:34.4341261][INFO/main.cpp:203] Fiber pool initialized.
[15:17:34.4350454][INFO/main.cpp:206] HTTP Client initialized.
[15:17:34.6835247][DEBUG/thread_pool.cpp:96] Thread 7236 executing font_mgr.cpp:103
[15:17:34.6840605][INFO/main.cpp:209] Translation Service initialized.
[15:17:34.7038912][INFO/main.cpp:212] Hooking initialized.
[15:17:34.7089215][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[15:17:34.7089329][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[15:17:34.7092573][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[15:17:34.7095719][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[15:17:34.7095792][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[15:17:34.7095906][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[15:17:34.7114500][DEBUG/thread_pool.cpp:96] Thread 7636 executing player_database_service.cpp:285
[15:17:34.7115992][INFO/main.cpp:233] Registered service instances...
[15:17:34.7117473][INFO/main.cpp:254] Scripts registered.
[15:17:34.7660302][INFO/main.cpp:257] Hooking enabled.
[15:17:34.7677919][INFO/main.cpp:260] Dynamic native hooker initialized.
[15:17:34.7686918][INFO/main.cpp:264] Lua manager initialized.
[15:17:34.8520882][INFO/backend.cpp:53] Starting script: Self
[15:17:34.8521464][INFO/backend.cpp:78] Starting script: Weapons
[15:17:34.8521567][INFO/backend.cpp:101] Starting script: Vehicles
[15:17:34.8521641][INFO/backend.cpp:117] Starting script: Miscellaneous
[15:17:34.8521903][INFO/backend.cpp:138] Starting script: Remote
[15:17:34.8521943][INFO/backend.cpp:153] Starting script: Ls customs
[15:17:34.8521970][INFO/backend.cpp:165] Starting script: Rainbow paint
[15:17:34.8521996][INFO/backend.cpp:177] Starting script: Disable Control Action
[15:17:34.8522023][INFO/backend.cpp:190] Starting script: World
[15:17:34.8658948][INFO/tunables_service.cpp:36] Loading tunables from cache
[15:17:48.2856329][INFO/main.cpp:272] Scripts unregistered.
[15:17:48.2856555][INFO/main.cpp:275] Lua manager uninitialized.
[15:17:48.3376596][INFO/main.cpp:278] Hooking disabled.
[15:17:48.3377581][INFO/main.cpp:281] Dynamic native hooker uninitialized.
[15:17:48.3377717][DEBUG/thread_pool.cpp:109] Thread 18620 exiting...
[15:17:48.3377770][DEBUG/thread_pool.cpp:109] Thread 5488 exiting...
[15:17:48.3377757][DEBUG/thread_pool.cpp:109] Thread 7236 exiting...
[15:17:48.7773333][DEBUG/thread_pool.cpp:109] Thread 7636 exiting...
[15:17:48.7777109][INFO/main.cpp:286] Destroyed thread pool.
[15:17:48.7777286][INFO/main.cpp:289] Script Connection Service reset.
[15:17:48.7789326][INFO/main.cpp:291] Tunables Service reset.
[15:17:48.7789390][INFO/main.cpp:293] Hotkey Service reset.
[15:17:48.7789411][INFO/main.cpp:295] Matchmaking Service reset.
[15:17:48.7789612][INFO/main.cpp:297] Player Database Service reset.
[15:17:48.7789634][INFO/main.cpp:299] API Service reset.
[15:17:48.7790577][INFO/main.cpp:301] Script Patcher Service reset.
[15:17:48.7790690][INFO/main.cpp:303] Gui Service reset.
[15:17:48.7793840][INFO/main.cpp:305] GTA Data Service reset.
[15:17:48.7793873][INFO/main.cpp:307] Vehicle Service reset.
[15:17:48.7793918][INFO/main.cpp:309] Model Preview Service reset.
[15:17:48.7794014][INFO/main.cpp:311] Mobile Service reset.
[15:17:48.7794042][INFO/main.cpp:313] Player Service reset.
[15:17:48.7794057][INFO/main.cpp:315] Pickup Service reset.
[15:17:48.7794085][INFO/main.cpp:317] Custom Text Service reset.
[15:17:48.7794149][INFO/main.cpp:319] Context Service reset.
[15:17:48.7794166][INFO/main.cpp:321] Xml Vehicles Service reset.
[15:17:48.7794175][INFO/main.cpp:322] Services uninitialized.
[15:17:48.7794465][INFO/main.cpp:325] Hooking uninitialized.
[15:17:48.7794520][INFO/main.cpp:328] Fiber pool uninitialized.

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

- **I removed all custom scripts, xmls, jsons, etc.. before producing a fresh log but the behavior is the same with or without additional content.**
- **Injector used : Xenos64 with default config.**
- **Game running on Windows 11 Pro version 22H3 build 22631.3155.**

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
probably a long shot but do you happen to have the the steam overlay enabled? If so try to disable it

**Comment by xesdoog** [comment]
> probably a long shot but do you happen to have the the steam overlay enabled? If so try to disable it

Thanks for replying
I disabled the overlay but the issue still persists.

**Comment by gir489returns** [comment]
Bug confirmed on latest master build. This was probably introduced with #2492 because of the way the console is handled now.

According to my debugger, the crash is coming from this function: 
![image](https://github.com/YimMenu/YimMenu/assets/100792176/10f30e6d-97a8-4672-b210-0730846b4ccf)

According to the Lumina repo, it is apart of a function chain called rage::phSimulator::FlushCollisionJobs. It is crashing because RSP is somehow null (what?)

**Comment by xesdoog** [comment]
@gir489returns Thanks for taking a look! I don't know if this helps _(probably not)_ but I've had this issue long before #2492.

**Comment by gir489returns** [comment]
> @gir489returns Thanks for taking a look! I don't know if this helps _(probably not)_ but I've had this issue long before #2492.

Yeah that commit has been a tumor since it's been merged... We need to have a dev discussion about rolling it back or something, it's caused nothing but issues.

**Comment by Yimura** [comment]
Fixed with #2858

**Comment by xesdoog** [comment]
Issue still there for me. I knew it wasn't related to #2492 because I've had it months before that commit. Honestly this could be an issue with my system since not many people have this problem so I don't think it's worth re-opening the issue. I've also tried Tupoye-Menu just to see if it crashes too and it does.
The console works flawlessly though!

Thank you guys for your hard work. We appreciate each and everyone of you ❤️

**Comment by xesdoog** [comment]
@Yimura @gir489returns @xiaoxiao921 If you're interested in knowing what was causing this, it was [Interception driver](https://github.com/oblitum/Interception) messing with ucrtbase.dll
Each time my game crashed when unloading the menu, my event viewer showed ucrtbase.dll as the faulting module and uninstalling Interception immediately solved the issue. I just loaded/unloaded YimMenu like 4 times in a row.
I tagged you here to say that this had nothing to do with YimMenu but if someone opens a similar issue in the future, asking them if they have Interception installed would make troubleshooting a bit easier since it's used by many people with disabilities but also **A LOT** of video-game cheaters.
